### ISSUE TITLE
Several Warnings in doveconf on Debian 7

### ISSUE THREAD

**Issue by Mutz** [Mins/TuxMail#6]
I'm using your scripts for the first Time on a new setup Debian 7 Server.

I have several Warnings in the doveconf:

Adding user xxx@zzz.com to /etc/dovecot/passwd. Please enter a password when prompted.
doveconf: Warning: NOTE: You can get a new clean config file with: doveconf -n > dovecot-new.conf
doveconf: Warning: Obsolete setting in /etc/dovecot/dovecot.conf:106: 'imaps' protocol is no longer necessary, remove it
doveconf: Warning: Obsolete setting in /etc/dovecot/dovecot.conf:106: 'pop3s' protocol is no longer necessary, remove it
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 109: Unknown setting: mechanisms
Creating user directory /home/vmail/zzz.com/xxx
Adding user to /etc/postfix/virtual_mailbox_users

There is no Prompt for the Password. I changed Line 26 in admin.sh to get doveadm working

**Comment by Mutz** [comment]
Got it... just had to change to DISTRO=2

**Comment by drmike** [comment]
Just to mention in case someone else comes by and sees this, you have to go ahead and delete the /etc/dovecot/dovecot.conf file before you run the install again.  If Debian sees it already there, it won't make the changes needed to run correctly.  I was not deleting it before rerunning and the file still had the information from the dovecot1.conf file which is what was creating these errors.

Maybe a check to see if the file exists and, if so, goes ahead and deletes it?

I'll leave this closed but I just wanted to add this in in case someone else has this error and can't recover from it like I did.
